set(_CATKIN_CURRENT_PACKAGE "polaris_sensor")
set(polaris_sensor_VERSION "1.0.1")
set(polaris_sensor_MAINTAINER "Antoine Hoarau <hoarau.robotics@gmail.com>")
set(polaris_sensor_PACKAGE_FORMAT "1")
set(polaris_sensor_BUILD_DEPENDS "geometry_msgs" "sensor_msgs" "serial" "roscpp" "cmake_modules")
set(polaris_sensor_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "sensor_msgs" "serial")
set(polaris_sensor_BUILDTOOL_DEPENDS "catkin")
set(polaris_sensor_BUILDTOOL_EXPORT_DEPENDS )
set(polaris_sensor_EXEC_DEPENDS "geometry_msgs" "roscpp" "sensor_msgs" "serial")
set(polaris_sensor_RUN_DEPENDS "geometry_msgs" "roscpp" "sensor_msgs" "serial")
set(polaris_sensor_TEST_DEPENDS )
set(polaris_sensor_DOC_DEPENDS )
set(polaris_sensor_DEPRECATED "")